// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int32     `json:"balance"`
	Currency  string    `json:"currency"`
	Createdat time.Time `json:"createdat"`
}

type Customer struct {
	Customerid   int32          `json:"customerid"`
	Customername string         `json:"customername"`
	Contactname  sql.NullString `json:"contactname"`
	Country      sql.NullString `json:"country"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	Orderid    int32     `json:"orderid"`
	Orderdate  time.Time `json:"orderdate"`
	Customerid int32     `json:"customerid"`
}

type Orderdetail struct {
	Orderdetailid int32 `json:"orderdetailid"`
	Orderid       int32 `json:"orderid"`
	Productid     int32 `json:"productid"`
	Quantity      int32 `json:"quantity"`
}

type Product struct {
	Productid     int32  `json:"productid"`
	Productname   string `json:"productname"`
	Price         string `json:"price"`
	Stockquantity int32  `json:"stockquantity"`
}

type Test struct {
	ID int64 `json:"id"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
